#!/bin/bash -e

echo '---
backup_should_be_locked_before:
- job_name: capi-consumer-1
  release: lock-ordering
- job_name: capi-consumer-2
  release: lock-ordering
restore_should_be_locked_before:
- job_name: redis-server
  release: redis-test
'
